# Setup
title:               Dive Data
tagline:             ~ Swim Far and Dive Deep
description:         place holder
url:
baseurl:             '/dive-data'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heng Li
  url:               https://github.com/hengli700
  email:             hengli700@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
