# Setup
title:               Dive Data
tagline:             ~ Swim Far and Dive Deep
description:         |
  Heng Li<br>
  MS in CS @ Georgia Tech<br>
  PhD in ME @ Northeastern

url:
baseurl:             '/dive-data'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Heng Li
  url:               https://github.com/hengli700
  email:             hengli700@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.2
# google_analytics_id: #UA-XXXX-Y
